"""Add relationships from user and class

Revision ID: 69971255bfca
Revises: bfc5114da6c1
Create Date: 2025-04-03 14:05:49.305864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69971255bfca'
down_revision: Union[str, None] = 'bfc5114da6c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('lessons', sa.Column('is_canceled', sa.Boolean(), nullable=False))
    op.drop_column('lessons', 'subject')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('subject', sa.VARCHAR(), nullable=False))
    op.drop_column('lessons', 'is_canceled')
    op.drop_table('subjects')
    # ### end Alembic commands ###
